# Generated by Django 5.0.14 on 2026-02-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_primary_role'),
        ('accounts', '0002_user_status'),
    ]

    operations = [
    ]
