services:
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${POSTGRES_DOCKER_HOST:-host.docker.internal}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      REDIS_HOST: ${REDIS_DOCKER_HOST:-host.docker.internal}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_DB: ${REDIS_DB:-0}
      CELERY_RESULT_DB: ${CELERY_RESULT_DB:-1}
      CELERY_BROKER_URL: ""
      CELERY_RESULT_BACKEND: ""
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
